### ISSUE TITLE
唉，注册都不能注册

### ISSUE THREAD

**Issue by lennondong** [lzwjava/LZAlbum#2]
点击注册提交，毫无反应。无法注册，就无法登陆，无法登陆，就啥也看不了。

**Comment by lzwjava** [comment]
@lennondong  

我刚刚试了下，是可以的，可以看看日志，或者贴上来，如

![image](https://cloud.githubusercontent.com/assets/5022872/8951670/3c93544e-3602-11e5-90ea-31552c22c05b.png)

看看是不是某个请求没有响应。

**Comment by lzwjava** [comment]
@lennondong 现在可以了吗？

**Comment by lennondong** [comment]
@lzwjava 我现在试一下。

**Comment by lennondong** [comment]
@lzwjava 我输完用户名和密码，点击注册按钮，依然什么反应都没有。我是4S设备。8.4系统。

**Comment by lennondong** [comment]
可以注册了。原来必须添加图片才可以。不添加，不行。也没有提示。
想问一下，我现在有服务器获取的数据，如果想用你的这个朋友圈UI，应该怎么做？复杂吗？

**Comment by lzwjava** [comment]
![demo1](https://cloud.githubusercontent.com/assets/5022872/8953441/0c02fd5c-3611-11e5-92ab-4cafc16af13a.gif)

**Comment by lzwjava** [comment]
好的，我加一些提示

**Comment by lzwjava** [comment]
https://github.com/lzwjava/LZAlbum/commit/461a1c68dec0e7dda22cd908db6db9556a097fdb

@lennondong 很容易的，这个很解耦。

UI 是从这里借鉴过来的， https://github.com/xhzengAIB/MessageDisplayKit ，原来的基础上改进了点赞和评论的UI。

**Comment by lennondong** [comment]
刚才在测试中，发现，网上拉拖动页面，拖动几次后，就闪退了。遇到起码3次。

**Comment by lennondong** [comment]
@lzwjava 好，我去看看这个kit。在我们项目中要加一个这个页面，朋友圈的这种。找了其他几个类似代码，不好用。

**Comment by lzwjava** [comment]
因为这个是开源的，管理台也可以登录，有些开发者乱改数据，搞得有些数据是异常的。

**Comment by lennondong** [comment]
哈哈，难怪。

**Comment by lennondong** [comment]
放弃了，太复杂了，完全不知道如何下手，没办法在我们的项目中使用。还是用其他的框架吧。
