### ISSUE TITLE
你好，我是iOS新手，请问cocoapods的问题怎么解决

### ISSUE THREAD

**Issue by LiverMore1314** [lzwjava/LZAlbum#4]
<img width="744" alt="2015-10-29 5 37 18" src="https://cloud.githubusercontent.com/assets/14848715/10814910/bbe36cd0-7e63-11e5-94c8-ffd59447ac29.png">

**Comment by lzwjava** [comment]
打开 *.xcworkspace

**Comment by LiverMore1314** [comment]
打开的是LZAlbum.xcworkspace,然后还是同样的三个错误额。

**Comment by lzwjava** [comment]
pod install

**Comment by lzwjava** [comment]
参考 https://github.com/CocoaPods/CocoaPods/issues/2303

**Comment by LiverMore1314** [comment]
已解决,谢谢

**Comment by mikiXuan** [comment]
Downloading dependencies
Installing AVOSCloud (3.1.6.2)
Installing DWTagList (0.0.7)
Installing DateTools (1.7.0)
Installing FXForms (1.2.14)
Installing MBProgressHUD (0.9.1)
Installing SDWebImage (3.7.3)
Generating Pods project
2015-11-17 15:43:42.129 ruby[2955:219670] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-9081/IDEFoundation/Initialization/IDEInitialization.m:590
Details:  Assertion failed: _initializationCompletedSuccessfully
Function: BOOL IDEIsInitializedForUserInteraction()
Thread:   <NSThread: 0x7fd686c282f0>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x0000000108780f86 -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:](in DVTFoundation)
  1  0x0000000108780713 _DVTAssertionHandler (in DVTFoundation)
  2  0x000000010878097f _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x00000001087808e1 _DVTAssertionFailureHandler (in DVTFoundation)
  4  0x000000010a4456ad IDEIsInitializedForUserInteraction (in IDEFoundation)
  5  0x000000010cc78081 +[PBXProject projectWithFile:errorHandler:readOnly:](in DevToolsCore)
  6  0x000000010cc79c06 +[PBXProject projectWithFile:errorHandler:](in DevToolsCore)
  7  0x00007fff925f8f44 ffi_call_unix64 (in libffi.dylib)
Abort trap: 6

我在下载第三方库的时候出现这个错误提示，然后项目运行不起来

**Comment by lzwjava** [comment]
好的，稍后我看看。请告知 pod 版本。

**Comment by hwx6678438** [comment]
如果我想用你的pods文件，我可以导入到自己的工程中吗？
